name: MythOfFive
main: com.mythof5.MythPlugin
version: 0.1.0
api-version: '1.20'
commands:
  myth:
    description: Myth administrative commands
    usage: /myth admin <subcommand>
    permission: myth.admin
  squad:
    description: Squad commands
    usage: /squad <subcommand>
    permission: myth.user.squad
permissions:
  myth.admin:
    description: Allows use of myth admin commands
    default: false
  myth.user.squad:
    description: Allows use of squad commands
    default: true
