boss:
  hp_default: 10000
  armor_default: 50
  name: "태초의 도깨비"
inherit:
  power_key: "dokkaebi.core"
  buffs:
    - "speed:1"
    - "strength:1"
  announce: true
  transfer_on_pvp_death: false
squad:
  max_members: 5
  friendly_fire: false
movement:
  double_jump:
    enabled: true
    vertical_velocity: 0.9
    forward_multiplier: 0.6
