boss:
  hp_default: 10000
  armor_default: 50
  name: "태초의 도깨비"
inherit:
  power_key: "dokkaebi.core"
  buffs:
    - "generic.max_health:set:40"
    - "generic.movement_speed:add:0.03"
    - "generic.attack_damage:add:2"
  announce: true
  transformation:
    default:
      scale_multiplier: 2.0
      attack_bonus: 6.0
      speed_bonus: 0.0
    aspects:
      power:
        scale_multiplier: 2.4
        attack_bonus: 9.0
        speed_bonus: 0.02
      speed:
        scale_multiplier: 1.8
        attack_bonus: 4.0
        speed_bonus: 0.08
      mischief:
        scale_multiplier: 1.9
        attack_bonus: 5.0
        speed_bonus: 0.05
      flame:
        scale_multiplier: 2.1
        attack_bonus: 5.5
        speed_bonus: 0.04
      forge:
        scale_multiplier: 2.35
        attack_bonus: 8.0
        speed_bonus: -0.01
squad:
  max_members: 5
  friendly_fire: false
movement:
  double_jump:
    enabled: true
    vertical_velocity: 0.9
    forward_multiplier: 0.6
hunter:
  release:
    low: 0.0052
    base: 0.1835
    slope: 0.012
    cap: 0.45
    fatigue_window_hours: 1.0
    fatigue_min: 0.7
    fatigue_max: 1.2
  gauge:
    gain:
      C: 7.0
      B: 9.0
      A: 11.0
      S: 12.0
  seal:
    patch_value: 20.0
    death_decay: 10.0
  event:
    witness_radius: 64.0
    broadcast_cooldown: 600.0
  omens:
    thresholds:
      long: 2
      medium: 4
      late: 5
  paradox:
    ritual_window: 600
    failure_scale: 1.5
