boss:
  hp_default: 10000
  armor_default: 50
  name: "태초의 도깨비"
inherit:
  power_key: "dokkaebi.core"
  buffs:
    - "generic.max_health:set:40"
    - "generic.movement_speed:add:0.03"
    - "generic.attack_damage:add:2"
  announce: true
  transformation:
    scale_multiplier: 2.0
    attack_bonus: 6.0
squad:
  max_members: 5
  friendly_fire: false
movement:
  double_jump:
    enabled: true
    vertical_velocity: 0.9
    forward_multiplier: 0.6
