name: mythof5
version: '${version}'
main: me.j17e4eo.mythof5.Mythof5
api-version: '1.21'
commands:
  myth:
    description: Myth administration commands
    usage: /myth admin <subcommand>
  squad:
    description: Squad management commands
    aliases: [sq]
    usage: /squad <subcommand>
  goblin:
    description: Goblin aspect commands
    usage: /goblin <subcommand>
  relic:
    description: Relic overview commands
    usage: /relic <subcommand>
  hunter:
    description: Hunter route commands
    usage: /hunter <subcommand>
  seal:
    description: Weapon sealing interface
    usage: /seal
